debug:   true

quotes.ribbon.listOfServers: localhost:8090

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [trace=%X{X-B3-TraceId:-},span=%X{X-B3-SpanId:-}] [%15.15t] %-40.40logger{39}: %m%n'

  level:
    QuoteClient: DEBUG

hystrix.command.greeting.execution.isolation.thread.timeoutInMilliseconds: 300

management:
  context-path: /monitor

security:
  ignored:    /
  user:
    name:     demo
    password: spr!ngD3M0

spring.cache:
  cache-names: greetings
  guava.spec: maximumSize=500,expireAfterAccess=30s
  
feign:
  user: marc
  pwd:  s0meth1ng2remember
  